BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE dienu_skaitu_saskaitisana';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE IZVEIDOT_KOPSAVILKUMU';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Maršruti_TRG"';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Braucieni_TRG"';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Maršruti_SEQ"';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Braucieni_SEQ"';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIENU_SKATS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MARŠRUTU_KOPSAVILKUMS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE KALENDĀRS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

ALTER TABLE BRAUCIENI DROP CONSTRAINT ROUTEID_F_CON;

DROP TABLE BRAUCIENI CASCADE CONSTRAINTS;

ALTER TABLE MARŠRUTI DROP CONSTRAINT ROUTESID_CON;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MARŠRUTI';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Service_SEQ"';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER Service_id_Braucieni_TRG';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE PARVEIDOT_BRAUCIENUS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PARVEIDOTI_BRAUCIENI';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER Vecais_Route_id_Trig';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
